#!/bin/bash
date=$(date "+%Y-%m-%d-%H-%M-%S")
tmp_avi=$(mktemp /tmp/gifcast_$date.avi)

if ! which ffcast >/dev/null
then
    echo "You'll need 'ffcast' for this script to work."
    exit 1
fi

ffcast -s % ffmpeg -y -f x11grab -show_region 1 -framerate 15
    -video_size %s -i %D+%c -codec:v huffyuv
    -vf crop="iw-mod(iw\\,2):ih-mod(ih\\,2)" $tmp_avi
&& convert -set delay 10 -layers Optimize $tmp_avi ~/Videos/gifcast_$date.gif
